[package]
name = "api-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.13"
