app_name = "api-server"

[server]
host = "127.0.0.1"
port = 8080

[logger]
service = "bch-keygen"
level = "debug"        # debug, info, warn, error

[db]
enabled = false
host = "127.0.0.1:3308"
dbname = "sample"
user = "hiromaily"
password = "hiromaily"
